### ISSUE TITLE
Make jump forward/ backward and the playback speed configurable

### ISSUE THREAD

**Issue by gijigae** [stefanbuck/logseq-media-controls#1]
Thank you so much for the plugin! Can we please make jump forward/backward and the playback speed configurable from the plugin settings?

**Comment by stefanbuck** [comment]
Hi, I would like to understand the current limitation you have to provide the best outcome for both of us. Although adding a settings page is simple it comes at a cost which was can make things difficult to change later, but I'm for discussion.

The current available values for the playback speed are 0.8, 1.0, 1.25, 1.5, 1.75 and 2.0. According to my research most players have similar values. Also it doesn't make a huge difference if you listen in 1.4 or 1.5 in my opinion. Please share your thoughts on this.

Same for the skip, 10 seconds seems to be quite common, although players use  30s. The idea was if you want to skip 30s, click the button three times, but I can see why you want to modify the value.

**Comment by gijigae** [comment]
I totally agree with the skip buttons. With regards to the play speed, I have seen many language learners who prefer to have play speed at more granular level since 0.8 is too slow. Also, at 0.8 speed, listeners often lose the original prosody of the speech. The other side of spectrum is also true. For many language learners, 1.25 is too fast. Hope you could consider these points in the next iteration.

**Comment by stefanbuck** [comment]
Thanks for sharing some additional context. I just added 0.9 and 1.1 as possible playback speeds in v0.1.0. Not sure how long it will take to become available on the marketplace ... I guess we will find out.

**Comment by stefanbuck** [comment]
The release didn't worked. I made the code change from my phone, but looks like making the release from my phone isn't straight forward. I'll look into tomorrow

**Comment by gijigae** [comment]
Noted. Again thank you so much for this plugin! Additional play speed will tremendously help many language learners. Will check it back later.

**Comment by gijigae** [comment]
Updated the plugin and confirmed the changes!
