### ISSUE TITLE
Command to activate {{renderer: media_controls}} doesn't work

### ISSUE THREAD

**Issue by BruceSaltzman** [stefanbuck/logseq-media-controls#2]
I discovered that manually pasting in {{renderer :media_controls}} activates the controls. I didn't notice the different placement of the colon at first.

**Comment by stefanbuck** [comment]
Awesome thanks. I just published `0.1.1` to fix the command

**Comment by BruceSaltzman** [comment]
Thank you, much appreciate. Great work.
