### ISSUE TITLE
Media controls won't render in sidebar

### ISSUE THREAD

**Issue by alizehctl** [stefanbuck/logseq-media-controls#3]
For some reason, media controls don't render when you open them as a block in sidebar.

https://user-images.githubusercontent.com/31581044/168424498-91f1af3c-04d2-4e13-bd10-614ae43f91b5.mp4

**Comment by alizehctl** [comment]
Hmm now they're rendering in the sidebar but not in the main document

![image](https://user-images.githubusercontent.com/31581044/168426700-4ab0e615-65a1-4409-80cd-4424cba4ffdc.png)

**Comment by alizehctl** [comment]
So it looks like it only renders one or the other, it can't render two instances of media controls for a single media source.

![image](https://user-images.githubusercontent.com/31581044/168426939-5352d5fb-a8cd-475d-a7a9-2a7217237469.png)

**Comment by stefanbuck** [comment]
Thanks for the detailed report, really appreciated. I just had a quick look, but seems to be related to Logseq itself. Multiple instances of the plugin does work in Logseq 0.6.6, but not in 0.6.7 or the latest version 0.6.8. I'll raise a bug report in Logseq.

**Comment by stefanbuck** [comment]
I opened an issue https://github.com/logseq/logseq/issues/5335

**Comment by stefanbuck** [comment]
Turns out the plugin requirements changed a little. I made a small change and now it is working again. Watch out for version `0.3.1`

**Comment by alizehctl** [comment]
@stefanbuck amazing! thank you
