### ISSUE TITLE
Can the maximum playback speed be adjusted to 4x?

### ISSUE THREAD

**Issue by UIyidu9322** [stefanbuck/logseq-media-controls#5]
That's a very useful plugin, thank you very much!
Can the maximum playback speed be adjusted to 4x?

**Comment by stefanbuck** [comment]
I just released a new version 0.4.0 which allows 4x speed. Please give it a try.

**Comment by stefanbuck** [comment]
There was an issue with the release process, but 0.4.0 is out now

**Comment by stefanbuck** [comment]
@UIyidu9322 there was an issue in the release process, which has been fixed and 0.4.0 is available now.
